
#  Swift 简单混淆脚本（Perl 替换版 - 更可靠）
#  使用: ./simple_confuse.sh -c  (混淆)  |  ./simple_confuse.sh -u (恢复)
SWIFT_CLASSES=(
    "AddImageCell"
    "AlertType"
    "AnimationConfig"
    "AnimationFastProcessor"
    "AnimationState"
    "AppConfig"
    "AppNotification"
    "AuthService"
    "AuthState"
    "AutoAdjustingTextView"
    "BannerCell"
    "BannerItemCell"
    "BaseSmartEngine"
    "BaseVC"
    "BaseWebView"
    "ButtonConfig"
    "CardFlipImageView"
    "CodingKeys"
    "ConnectionState"
    "ConnectionType"
    "Constants"
    "CornerPosition"
    "CustomAlertView"
    "CustomModernHelper"
    "CustomSegmentView"
    "CustomView"
    "DYAIModel"
    "DYAlertView"
    "DYAutoFactory"
    "DYBannerView"
    "DYChargeProgressView"
    "DYDiamondBuyVC"
    "DYDiamondBuyVCDelegate"
    "DYDrawDressupVC"
    "DYDrawFreeStyleVC"
    "DYDrawMagicBrushVC"
    "DYDressupBottomView"
    "DYDressupBottomViewDelegate"
    "DYFeedVC"
    "DYFivePicInterPageVC"
    "DYGetFileSizeTool"
    "DYIAPManager"
    "DYIMageTools"
    "DYImageAndTextToVideoParentVC"
    "DYImageTextToVideoUIManager"
    "DYImageTextToVideoUIManagerDelegate"
    "DYImageTextToVideoVC"
    "DYInputStackView"
    "DYInputStackViewDelegate"
    "DYInterpage"
    "DYKissList"
    "DYKissListCell"
    "DYKissListChildVC"
    "DYKissListChildVCDelegate"
    "DYKissResultVC"
    "DYKissSelectPicUIManager"
    "DYKissSelectPicVC"
    "DYLM"
    "DYLoadingView"
    "DYLogLevel"
    "DYLogger"
    "DYMineVC"
    "DYMyWorksAndVideoVC"
    "DYMyWorksNetVC"
    "DYMyWorksVC"
    "DYNNetworkMonitor"
    "DYNetworkManager"
    "DYNetworkMonitor"
    "DYNewHome"
    "DYNumberSelectView"
    "DYNumberSelectViewDelegate"
    "DYOnlineSubscribeCountVC"
    "DYOnlineSubscribeCountVCDelegate"
    "DYPhoTopsHome"
    "DYPicAndVideoHome"
    "DYProgressBarView"
    "DYProgressHUD"
    "DYPromptSelectView"
    "DYPromptSelectViewDelegate"
    "DYRequestTool"
    "DYSaveImageManager"
    "DYSectionCollectionView"
    "DYSectionCollectionViewDelegate"
    "DYSegmentView"
    "DYSubscribeParentVC"
    "DYSubscribeProVC"
    "DYSubscribeProVCDelegate"
    "DYTemplateChildVC"
    "DYTemplateChildVCDelegate"
    "DYTemplateVC"
    "DYTextToVideoModelDataManager"
    "DYTextToVideoModelDataManagerDelegate"
    "DYTextToVideoUIManager"
    "DYTextToVideoUIManagerDelegate"
    "DYTextToVideoVC"
    "DYThreeItemCheckView"
    "DYTimer"
    "DYUITools"
    "DYVideoModelDataManager"
    "DYVideoModelDataManagerDelegate"
    "DYVideoPlayTool"
    "DataModel"
    "DealPicViewController"
    "DealPicViewUI"
    "DescriptionPopupView"
    "DotConfiguration"
    "DownloadProgressBar"
    "DownloadState"
    "Downloader"
    "DrawMode"
    "DurationConfig"
    "DurationOption"
    "Environment"
    "EraseTwoImageView"
    "FeedImageCell"
    "FloatingButtonManager"
    "FloatingPopupView"
    "FunctionCell"
    "FunctionItem"
    "GIFPlaceholderImageView"
    "GradientButton"
    "GradientDirection"
    "HTTPMethodType"
    "HUDManager"
    "HUDType"
    "ImageContentViewController"
    "ImageFadeView"
    "ImageGalleryViewController"
    "ImageLoader"
    "ImageLoadingDelegate"
    "ImageManager"
    "ImagePickerType"
    "ImagePosition"
    "ImagePreviewViewController"
    "ImageProcessingService"
    "ImageTransitionView"
    "ImageTransitionViewDelegate"
    "InputType"
    "JSAdfzlsrFuALPType"
    "JXHorizonAlignment"
    "JXPageControlAlignment"
    "JXPageControlType"
    "JXVerticalAlignment"
    "LLAccessibilityAlertController"
    "LLNetworkAccessibility"
    "Language"
    "MZRefreshComponent"
    "MZRefreshConfig"
    "MZRefreshDate"
    "MZRefreshFooterComponent"
    "MZRefreshGifFooter"
    "MZRefreshGifFooterContent"
    "MZRefreshGifHeader"
    "MZRefreshGifHeaderContent"
    "MZRefreshHeaderComponent"
    "MZRefreshNormalFooter"
    "MZRefreshNormalFooterContent"
    "MZRefreshNormalHeader"
    "MZRefreshNormalHeaderContent"
    "MZRefreshOnlyGifHeader"
    "MZRefreshOnlyGifHeaderContent"
    "MZRefreshStatus"
    "ManageableNHybuYHQUb"
    "ManageablernFmTay"
    "ManagerAutoView"
    "MaskImageProcessor"
    "MovementAmplitudeConfig"
    "MovementOption"
    "Mp4CollectionViewCell"
    "MultiArrayType"
    "NetworkMonitor"
    "NetworkResponse"
    "NetworkSmartHandler"
    "NetworkStatus"
    "NetworkType"
    "NotificationCleaner"
    "NotificationHandler"
    "NotificationTool"
    "ObservableSwsnAxIlfOchQ"
    "PicCollectionViewCell"
    "PipelineLoader"
    "PipelinePreparationPhase"
    "PriceCacheItem"
    "PriceCacheManager"
    "ProcessableUitYCTrLODa"
    "PromptSection"
    "QPfJBBLPcWEbData"
    "RandomQueue"
    "RecognizedObject"
    "ResolutionConfig"
    "ResolutionOption"
    "RestoreResult"
    "SAM2"
    "SAM2Error"
    "SAM2Pipeline"
    "SAMBox"
    "SAMCategory"
    "SAMCategoryType"
    "SAMPipelineError"
    "SAMPoint"
    "SAMSegmentation"
    "SAMTool"
    "SceneType"
    "ScreenBrightnessManager"
    "ScreenInsetsUtil"
    "SectionHeaderView"
    "SectionModel"
    "SegmentCell"
    "SensitiveWordFilter"
    "StoreError"
    "SubViewData"
    "TMCuOhsdpqMData"
    "TTVDurationConfig"
    "TTVDurationOption"
    "TTVModel"
    "TTVModelContainer"
    "TTVMovementAmplitudeConfig"
    "TTVMovementOption"
    "TTVResolutionConfig"
    "TTVResolutionOption"
    "TTVStyleConfig"
    "TTVStyleOption"
    "TemplateCell"
    "TrieNode"
    "UIGenerateVC"
    "UIResultVC"
    "Util"
    "VHqGdXfasfkyData"
    "VideoCacheManager"
    "VideoModel"
    "VideoModelContainer"
    "VideoModelError"
    "VideoModelListView"
    "VideoModelListViewController"
    "VideoModelSelectorView"
    "VideoModelUtils"
    "VideoPlayerCell"
    "VideoPlayerManager"
    "VideoThumbnailCache"
    "XawaDealPicViewController"
    "XawaDownloadVC"
    "XawaHomeVC"
    "XawaInterPageVC"
    "XawaKiss"
    "XawaMyWorkVC"
    "XawaRamdonGenerateVC"
    "YCHomeCacheType"
    "YCKissInterpage"
    "YCLocalDataSaveUtil"
    "YCkissTemplateCell_meth"
    "YoloPipeline"
    "drawHistoryData"
    "dyImagePreviewViewController"
    "loadingAndAlert"
    "myWorksAndVideoItemCollectionViewCell"
    "myWorksItemCollectionViewCell"
    "picParentView"
    "rXuwTSEiIavData"
    "textimageToVideo"
    "threePicAnimationView"
    "twoPicAnimationView"
    "userInfoView"
    "videoParentView"
    "xuanfu"
    "yoloBoundingBoxView"
)

# 方法名数组 (993个)
SWIFT_METHODS=(
    "AsyncserializeItemEzmzIZps"
    "AsyncserializeItemmGFOlvps"
    "AutomanageContentCNxNfjwAXlj"
    "AutomanageContentkjajQlmiUFV"
    "AutomanageDataHPoZitSCn"
    "AutooptimizePayloadPxgNmvl"
    "AutooptimizePayloadaDUGqgB"
    "AutoperformContentZDHUBuHkapi"
    "AutoperformContentdRMzrOfcDkw"
    "AutoperformContentfRnoXqVzrrx"
    "AutoperformContentoxpTMVsQuon"
    "BoundingBox"
    "DYLog"
    "FastauthenticateStateJtpyPcTSXgtzS"
    "FastauthenticateStateULfZTRkHhRHOS"
    "FastauthenticateStateUuZAbXUlGpyOR"
    "FastauthenticateStateWFDGzWhtZUydM"
    "FastauthenticateStateaSDFpoZhvzdUZ"
    "FastauthenticateStatehzFaZLggdzCVq"
    "FastauthenticateStateqohvZAtgxVEXN"
    "FastauthenticateStatewCXPRvEmWrVVy"
    "FastauthenticateStatewYJAWCSGcTEUS"
    "FastauthenticateStateyoyocVFrXyXHx"
    "FastauthenticateTokenNDExvKj"
    "FastexecutePayloadpMPbMDrOfnaQBf"
    "FastoptimizeStateHzIWsmPFSuW"
    "FastoptimizeStateIOKNAMQlXyi"
    "FastoptimizeStatePJMtyWUwrMD"
    "FastoptimizeStatemYlTbuQvgiG"
    "FastoptimizeStatepPKPDCBzcaK"
    "FastoptimizeStateubnCqVlzfVK"
    "FastprocessStateBiGakkUNEed"
    "FastprocessStateDfwHQJIhElw"
    "FastprocessStateGvtuDUVLEWB"
    "FastprocessStateHzWqJalEfdL"
    "FastprocessStateLOUxHuDFWwP"
    "FastprocessStateOjDGATyyGtf"
    "FastprocessStateUTWzXuxoFQy"
    "FastprocessStateakVvNfHjHZS"
    "FastprocessStatefnmeehSViYB"
    "FastprocessStatevpzjKQYAgsr"
    "FastserializeInfovamWRBZHZq"
    "FasttransformStateRfwkNfOdc"
    "FasttransformStatebnmARPaHv"
    "FasttransformStatepeCeavtFU"
    "FasttransformStateqKzsqGHlp"
    "FastvalidatePayloadoDFcQ"
    "KeywordNoPass"
    "SafecalculateSessionbcJRFWhVVE"
    "SafeencryptSessionEzAmYTpu"
    "SafeencryptSessionhbTMwGJJ"
    "SafeencryptSessionjcPAEDRp"
    "SafesynchronizeConfigCOLxFBfLqWtkzH"
    "SafesynchronizeConfigffKlOGfaJKzdBY"
    "SecurehandleMetadatajkQJwimCaM"
    "SecureperformContentNMCCc"
    "SecuresynchronizeInfozBKCQrxd"
    "ShowProgressHUDLoading"
    "SmartencryptItemiLMibzId"
    "SmartexecuteItemXiviOdUSrP"
    "SyncauthenticateCacheNEcfKhOETRJKa"
    "SyncauthenticateCachekgYlAzgWimAur"
    "SyncsynchronizeSessionZUJNEAeLoQAG"
    "YCclearGifResources_meth"
    "YCconfigure_meth"
    "YCdetermineSelectedItem_meth"
    "YCdismissGif_meth"
    "YCgetDrawItemsData_meth"
    "YChandleError_meth"
    "YChandleSuccessResponse_meth"
    "YCpostMaidian_meth"
    "YCsetupUI_meth"
    "YCshowGifAnimation_meth"
    "YCupdateCurrentIndex_meth"
    "YCupdatePageIndicator_meth"
    "YCupdateSelectedItemProperties_meth"
    "YCupdateUI_meth"
    "activeHollowLayout"
    "addAndLayoutAlertView"
    "addButtonTargets"
    "addFrostedGlassEffect"
    "addGestureRecognizers"
    "addGradientShadowToVideoView"
    "addImageViewConstraints"
    "addLayoutSubview"
    "addObserverOnce"
    "addPulseAnimation"
    "addReachabilityCallBack"
    "addRefreshObserver"
    "addRotation"
    "addToDrawHistoryDataList"
    "addToMaskImageHistoryList"
    "addWord"
    "addWords"
    "aidressGotoGennerateVC"
    "animateProgress"
    "appendData"
    "applyingThreshold"
    "attach"
    "backButtonTapped"
    "backVC"
    "bestMask"
    "bottomView"
    "bottomViewClickFirstLevelCustomBtn"
    "bottomViewClickVipmaterialUserIsNoVip"
    "bottomViewDidTapStartButton"
    "bottomViewbackStepTapped"
    "cacheVideo"
    "calculateHeightForSection"
    "calculateNavigationBarAndTabBarHeights"
    "cancelCurrentImageLoading"
    "cancelImageLoading"
    "centerImageView"
    "changeLocalVideoSource"
    "changeVideoSource"
    "checkAndAnimateNext"
    "checkAndResetPosition"
    "checkAndUpdateButtonAppearance"
    "checkAndUpdateButtonState"
    "checkCameraPermission"
    "checkCellVisibility"
    "checkInputWordsInfo"
    "checkKeyWords"
    "checkMemory"
    "checkModelSize"
    "checkNetWork"
    "checkPhotoLibraryPermission"
    "checkUserIsProVip"
    "checkUserIsVip"
    "checkVerified"
    "checkuserNotificationOpenStatus"
    "chooseValue"
    "chooseValueIfAHaveValueOrB"
    "clamp"
    "cleanCacheIfNeeded"
    "cleanup"
    "cleanupNetworkMonitor"
    "cleanupTmpDir"
    "clearAll"
    "clearAllCache"
    "clearAllCachedData"
    "clearAllCaches"
    "clearAllText"
    "clearBadge"
    "clearButtonTapped"
    "clearCache"
    "clearCacheData"
    "clearDrawData"
    "clearFeatureStackView"
    "clearGifResources"
    "clearSelection"
    "clearText"
    "clearTextContent"
    "clearYoloButtonSelections"
    "colorDistance"
    "commonInit"
    "compositeImages"
    "compressImage"
    "compressImageIfNeeded"
    "compressToFileSize"
    "configAlert"
    "configureActionButtons"
    "configureBottomButton"
    "configureBrushSizeControls"
    "configureCardFlipView"
    "configureConfigKJjsSxqI"
    "configureConfigecvamdlj"
    "configureCreateBtn"
    "configureDescriptionView"
    "configureDrawToolsView"
    "configureForPreiOS13"
    "configureForiOS13AndLater"
    "configureImageView"
    "configureInputtextViewTipLabel"
    "configureModelConfigView"
    "configureModelOptionButton"
    "configureModelSelectionPopup"
    "configureOneAnimationBigView"
    "configureOptionButton"
    "configureParametersDisplayView"
    "configurePlacePicsViewAndUploadBtn"
    "configurePromptTextView"
    "configureQuickAndDrawView"
    "configureScrollView"
    "configureStyleOptionButton"
    "configureTableView"
    "configureTipLabel"
    "configureTopImageView"
    "configureYoloView"
    "consumePreviewStream"
    "contentHeight"
    "convertTouchPointToImagePoint"
    "coverPicToPic"
    "coverPicWithMaskPic"
    "createAnimationFastProcessor"
    "createBaseSmartEngine"
    "createBottomSheet"
    "createButton"
    "createCustomModernHelper"
    "createDYAutoFactory"
    "createDownLoadProgressView"
    "createEmptyImage"
    "createFeatureView"
    "createIconButton"
    "createImageView"
    "createInputView"
    "createLabel"
    "createMD5String"
    "createManagerAutoView"
    "createNetworkSmartHandler"
    "createNewRow"
    "createNumberButton"
    "createOZUgzOo"
    "createOnlineButton"
    "createOrderInfo"
    "createProgressPath"
    "createPromptButton"
    "createPromptScrollView"
    "createPromptStackView"
    "createQuickAndBlushButton"
    "createSliderThumbImage"
    "createStripePath"
    "createSubView"
    "createSubscriptionOptionView"
    "createThumbImage"
    "createVideoButtonTapped"
    "createVideoView"
    "createView"
    "createcklORTnaRb"
    "createeqwmb"
    "cropImageWithRect"
    "cropImageWithRectFromPic"
    "currentReachable"
    "currentViewController"
    "cutImage"
    "cutImage1"
    "dataListIsEmpty"
    "dataManagerDidFailWithError"
    "dataManagerDidUpdateModels"
    "dealError"
    "dealFinalImageAndDotAndHistoryList"
    "dealLoginError"
    "dealSegmentChange"
    "dealSocketError"
    "dealWithGenerateKissVideo"
    "dealWithGeneratePic"
    "dealWithQuickResult"
    "decodeStringToJsonWithString"
    "delSuccessToDealItemsData"
    "deleteAllCloudHistoryListByIds"
    "deleteAllHistoryListByIds"
    "deleteCloudHistoryListByIds"
    "deleteHistoryListByIds"
    "deleteImage"
    "deleteLocalHistoryList"
    "denormalize"
    "diamandUploadPic"
    "didScroll"
    "disableAlwaysOn"
    "dismissAllControllerHUDs"
    "dismissGif"
    "dismissModelSelection"
    "downloadModel"
    "downloadModelFailReward"
    "drawDot"
    "drawDotOnImage"
    "drawImageOnCanvas"
    "drawImageOnCanvasToWH512"
    "drawMask"
    "drawTogenerate"
    "drawUploadPicWithImageAndType"
    "dressPicGotoGennerateVC"
    "dsprunToGeneratePic"
    "durationButtonTapped"
    "dyJsonString"
    "dy_getNomalParamsDic"
    "dy_getUUID"
    "enableAlwaysOn"
    
    "ensureModelsAreLoaded"
    "enterFullscreen"
    "eraseArea"
    "eraseFinalImg"
    "eraseWhiteAreaFromMask"
    "executeModelGeneration"
    "exitFullscreen"
    "extractResponseCode"
    "findAivideoButton"
    "findModel"
    "flashBorder"
    "formatSize"
    "freeStyleGotoGennerateVC"
    "fromSize"
    "furthestColor"
    "generateRandomString"
    "getAIConfigSetting"
    "getAccountInfoData"
    "getAiConfigSettingInfo"
    "getAllImageNames"
    "getAllImageNamesWithFullPath"
    "getAllModelLabels"
    "getCacheData"
    "getCacheFileName"
    "getCachedModels"
    "getCachedModelsIfAvailable"
    "getCachedVideoURL"
    "getCellHeightRatioByType2"
    "getCloudHistoryList"
    "getConfigWithKey"
    "getCoustomPrompt"
    "getCreateTasksListData"
    "getCreateVideoConfigPrice"
    "getCreateVideoModelParams"
    "getCurrentDurationKey"
    "getCurrentDurationOptions"
    "getCurrentLanguage"
    "getCurrentModel"
    "getCurrentModelKey"
    "getCurrentMotionKey"
    "getCurrentMotionOptions"
    "getCurrentResolutionKey"
    "getCurrentResolutionOptions"
    "getCurrentStyleKey"
    "getCurrentStyleOptions"
    "getCurrentWindow"
    "getDefaultValue"
    "getDeviceIdFromKeychain"
    "getDeviceModelIdentifier"
    "getDocumentsFolderSize"
    "getDrawItemsData"
    "getDurationOptions"
    "getFirstAvailableModel"
    "getForceUpdateSettingInfo"
    "getFormattedPrice"
    "getHistoryList"
    "getHomeAIDrawUpList"
    "getHomeSwiperData"
    "getImage"
    "getImageDisplayRect"
    "getImageEncoding"
    "getImgMd5WithBase64"
    "getIphoneTotalMemory"
    "getLastTaskData"
    "getLocalHistoryList"
    "getMask"
    "getMaskIMGWithTapLocation"
    "getMessageListData"
    "getModelCount"
    "getMovementOptions"
    "getMsgClaim"
    "getMutleFormattedPrice"
    "getNewCode"
    "getOptimizeData"
    "getOptimizeNewCode"
    "getOriginalURL"
    "getPicDrawArrData"
    "getPrefixBeforePipe"
    "getPrice"
    "getPricingInfo"
    "getPromptEncoding"
    "getScreenLayoutDirectionIsRTL"
    "getSegmentItems"
    "getSelectedItems"
    "getStringFromUserDefaults"
    "getSwiperViewData"
    "getSystemLanguageCode"
    "getTextContent"
    "getTwoPeopleImages"
    "getUploadPicData"
    "getVideoData"
    "getVideoListData"
    "getVideoModelData"
    "getVideoModels"
    "getVideoModelsAsync"
    "getVideoTemplateData"
    "getVideoURL"
    "getZPositions"
    "gifImageWithData"
    "goBackgroundShowAlertWithTitleAndButton"
    "goback"
    "gobackToListVC"
    "gotoGennerateVC"
    "gotoVideoGeneraeteWithUploadThePic"
    "gotogeneratePicVC"
    "handleBSOiHgQhoOCwF"
    "handleCacheAndNetworkUpdate"
    "handleCellTapped"
    "handleGenerationResult"
    "handleHzJtbNEQO"
    "handleJPushUserInfo"
    "handleKdstXK"
    "handleLOdcDVyXOkEOv"
    "handleNjvGMlzTnazAyD"
    "handleNrloeslU"
    "handleOnlineButtonTapped"
    "handlePkuVW"
    "handleQNDiTuYvDJDNjN"
    "handleResponseWithCache"
    "handleSHpSBgGOlVu"
    "handleSaveCompletion"
    "handleSortingForStrArray"
    "handleSwiperTapped"
    "handleTVQNFOmYYi"
    "handleTransactions"
    "handleUpzCpOHCkgRphq"
    "handleVisibilityChanged"
    "handleVkBQzsRyXMcfOF"
    "handleWjNUPpqj"
    "handleepmUMFfzSybq"
    "handleevQKqwNqqcjxoC"
    "handleiAUpXeSwnskUV"
    "handleiZAQMc"
    "handleykxHEtVsV"
    "hasCachedData"
    "hasEnoughFreeDiskSpace"
    "hiddenAlert"
    "hiddenDownLoadProgressView"
    "hiddenSelectButton"
    "hideDownloadAlert"
    "hideDrewPicView"
    "hideLoading"
    "hollowLayout"
    "imageLoadingCompleted"
    "imagePreviewViewController"
    "imageToBase64"
    "imageTransitionView"
    "imgcv"
    "inactiveHollowLayout"
    "initStateWithLocalModel"
    "initThird"
    "initializeGeneration"
    "initializeInfoGQcmIBvunHMjzuqu"
    "initjiguang"
    "inputStackView"
    "inputStackViewDidClickCloseBtn"
    "isIPad"
    "isInputValid"
    "isMoreLongSizeLanguage"
    "isNetworkAvailable"
    "isSimulator"
    "isTextValid"
    "isUploadingPic"
    "isUseWWANConnect"
    "isUseWifiConnect"
    "isVideoCached"
    "isVipDataEqual"
    "ishaveImgAndhaveInputtext"
    "jsonStringToModel"
    "judgeDayTimes"
    "judgeGotoDescribeVC"
    "judgeNework"
    "kissListChildVC"
    "layoutActiveIndicator"
    "layoutContentView"
    "layoutInactiveIndicators"
    "loadAiSettingData"
    "loadAiSettingDataFromCache"
    "loadAndCompressImage"
    "loadCache"
    "loadCachedData"
    "loadCachedOrderInfo"
    "loadCachedVideos"
    "loadCreatingData"
    "loadDictArray"
    "loadFromLocalFile"
    "loadFromServer"
    "loadGif"
    "loadImageAtIndex"
    "loadImageFromDisk"
    "loadModels"
    "loadProduct"
    "loadSectionsFromCache"
    "loadSensitiveWords"
    "loadStringArray"
    "loadSwiperData"
    "loadSwiperDataFromCache"
    "loadVideoModels"
    "loadVipDataFromCache"
    "loadlongData"
    "maskedToAlpha"
    "md5HashWithImage"
    "mergeTwoImages"
    "modelOptionTapped"
    "modelSelectButtonTapped"
    "modelToggleButtonTapped"
    "motionButtonTapped"
    "noPhotoAlbumToOpenSettings"
    "notifyChildControllersToUpdateUI"
    "numberSelectView"
    "onVideoPlaybackFailure"
    "onVideoPlaybackSuccess"
    "openAppStore"
    "openCurrentAppInAppStore"
    "openInSafari"
    "parseDurationConfig"
    "parseDurationOption"
    "parseModelsFromServerData"
    "parseMovementConfig"
    "parseMovementOption"
    "parseResolutionConfig"
    "parseResolutionOption"
    "parseServerData"
    "parseStatus"
    "parseStyleConfig"
    "parseStyleOption"
    "parseVideoModel"
    "parseVideoModelsFromData"
    "parseVideoModelsFromServerData"
    "pauseAllMp4Videos"
    "pauseAllVideos"
    "performDataLJbBjGsOU"
    "playLastVideo"
    "playVideo"
    "postAccountData"
    "postBurialpointInfo"
    "postCheckOrderInfo"
    "postDrawResultData"
    "postFeed"
    "postLogin"
    "postLoginData"
    "postMaidian"
    "postOrderInfo"
    "postTimerMaidian"
    "postUserHaveAdCount"
    "postUserLookAdCompelete"
    "postjiguangregistrationID"
    "postmaidian"
    "precalculateHeights"
    "prefetchBannerImages"
    "prefetchFunctionImages"
    "prepareFinalDrawPic"
    "prepareForImage"
    "prepareModelInput"
    "presendSubScribeVC"
    "preventRepeatedPresses"
    "previewDeleteUrlPicWithImageName"
    "previewImageDeleteLocalPicWithImageName"
    "processDataSource"
    "processDataTmVuYgRxYQw"
    "processDataduqykcpIVBm"
    "processFailedGeneration"
    "processImg2VideoPricing"
    "processResultImages"
    "processText2VideoPricing"
    "promptSelectView"
    "promptSelectViewDidCancel"
    "pushAndRemoveMiddlePages"
    "pushAndRemoveSelf"
    "pushDYMyWorksAndVideoVC"
    "pushDownLoadPageVC"
    "pushFeedVC"
    "pushLocalDrawPageVC"
    "pushSubScribeVC"
    "pushToInterPageVC"
    "pushToSubscribeVC"
    "putImageData"
    "qualityButtonTapped"
    "randomCandidateColor"
    "readFromKeychain"
    "refreshAllData"
    "refreshCloudData"
    "refreshUI"
    "registerHDSCrYta"
    "registerbjmqbkVo"
    "registerhmDrslVjQBCpt"
    "registeriVXUNxW"
    "registerrqFBCDrsvLDw"
    "registerxZUElZFFeF"
    "releaseResources"
    "releaseSam2Model"
    "reloadLayout"
    "reloadResources"
    "reloadSam2"
    "reloadSam2Model"
    "removeAllBoundingBoxes"
    "removeFrostedGlassEffect"
    "removeLoadingIndicator"
    "removeNotifications"
    "removePlayerObservers"
    "removeRefreshFooter"
    "removeRefreshHeader"
    "removeRefreshNoMoreDataView"
    "removeRefreshObserver"
    "replaceSelectedImage"
    "requestCloudData"
    "resetActiveLayer"
    "resetGifLoadTimeReported"
    "resetHidden"
    "resetInactiveLayer"
    "resetProduct"
    "resetSelectionIndices"
    "resetToDefaultState"
    "resetZoom"
    "resetZoomAndLayout"
    "resizeImage"
    "restartPulseAnimation"
    "safelyUpdateSectionView"
    "samTinted"
    "saveAiSettingData"
    "saveAiSettingDataToCache"
    "saveCache"
    "saveCacheData"
    "saveDictArray"
    "saveImage"
    "saveImageToAlbum"
    "saveImageToDisk"
    "saveOneVideo"
    "savePicsOrVideo"
    "savePrice"
    "savePricingInfo"
    "saveResultImageToLocal"
    "saveSectionsToCache"
    "saveStringArray"
    "saveStringToUserDefaults"
    "saveSwiperData"
    "saveSwiperDataToCache"
    "saveToAlbum"
    "saveToKeychain"
    "saveVideosWithUrls"
    "saveVipDataToCache"
    "scrollToBottom"
    "selctPicOrcamera"
    "selectButton"
    "selectDurationButton"
    "selectDynamicDurationButton"
    "selectDynamicModelButton"
    "selectDynamicMotionButton"
    "selectDynamicQualityButton"
    "selectDynamicStyleButton"
    "selectImageButtonTapped"
    "selectModel"
    "selectMotionButton"
    "selectQualityButton"
    "selectSegment"
    "sendGeneratePicMessage"
    "sendGenerateRamdonPicMessage"
    "sendGetGenerateProgressMessage"
    "sendGetKissProgressMessage"
    "sendKissPicMessage"
    "sendLoginMessage"
    "setBackgroundColor"
    "setBase"
    "setBottomBtnWithState"
    "setBottomSheetViewResultImageView1Hidden"
    "setButtonSelected"
    "setDefaulPlaceGifImage"
    "setDefaultDurationSelection"
    "setDefaultGifBackgroundImage"
    "setDefaultLevelSelection"
    "setDefaultModelSelection"
    "setDefaultMotionSelection"
    "setDefaultQualitySelection"
    "setDefaultSegment"
    "setDefaultSelections"
    "setDefaultStyleSelection"
    "setGotoOnlineViewHiddenOrShow"
    "setHDButtonHidden"
    "setImagePosition"
    "setImageUrls"
    "setInitSegmentsToolsViewselectIndex"
    "setInitialState"
    "setInitialTexts"
    "setLooping"
    "setPlacePicsViewAndUploadBtnHidden"
    "setReplaceObjectsText"
    "setReplacedPhotoText"
    "setResultPicWith"
    "setSegmentsToolsViewSelected"
    "setSelectedItem"
    "setTextContent"
    "setTextInputContent"
    "setToolButtonSelected"
    "setTopImageViewWithNewOriginPic"
    "setUpTabbar"
    "setUpUIWithItemCount"
    "setVideoPlayerViewRecommended"
    "setupBackButton"
    "setupBannerImages"
    "setupBaseView"
    "setupBasicUI"
    "setupBottomView"
    "setupButtons"
    "setupCell"
    "setupChildViewControllers"
    "setupCloudOrLocalSegmentControl"
    "setupCollectionView"
    "setupCommonInit"
    "setupConnectionTimeout"
    "setupContainerView"
    "setupContent"
    "setupControlsUI"
    "setupCoverBgImageView"
    "setupCoverMoveImageView"
    "setupCoverMoveImageView1"
    "setupDataManager"
    "setupDiamondButton"
    "setupDownloadProgressSubscription"
    "setupDrawViewsLayout"
    "setupDurationConstraints"
    "setupEmptyView"
    "setupErrorView"
    "setupFeatures"
    "setupImageLayout"
    "setupImageObserver"
    "setupImageView"
    "setupImageViews"
    "setupImageViewsWithUrls"
    "setupLeftAndRightBarButton"
    "setupLoadingIndicator"
    "setupLocalVideo"
    "setupMainButtonsLayout"
    "setupMainConstraints"
    "setupModelOptions"
    "setupModelOptionsConstraints"
    "setupModelSelectOptions"
    "setupModelSelectionConstraints"
    "setupMonitor"
    "setupMotionConstraints"
    "setupMotionOptions"
    "setupNavigationBarButton"
    "setupNetworkAccessibility"
    "setupNetworkMonitoring"
    "setupNetworkVideo"
    "setupNotifications"
    "setupOneImageViewLayout"
    "setupOperationView"
    "setupPageViewController"
    "setupPhotoAndVideoSegmentView"
    "setupPlayerViewConstraints"
    "setupProgressMonitoring"
    "setupProgressView"
    "setupPromptButtons"
    "setupPromptClearButton"
    "setupPromptInputView"
    "setupPromptPlaceholder"
    "setupPromptScrollViews"
    "setupPromptTextView"
    "setupPromptTextViewCallback"
    "setupQualityConstraints"
    "setupQualityOptions"
    "setupRTLConstraints"
    "setupRTLSupport"
    "setupRemindButton"
    "setupRightBarButton"
    "setupScrollView"
    "setupScrollViewDelegates"
    "setupSegmentControlLayout"
    "setupSegmentView"
    "setupSegments"
    "setupStyleConstraints"
    "setupStyleOptions"
    "setupTermsButtons"
    "setupTitleViewSegmentControl"
    "setupTopFeatures"
    "setupTopImageView"
    "setupTopImageViewGestures"
    "setupTwoImageViewLayout"
    "setupUI"
    "setupUIManager"
    "setupUIWithViewController"
    "setupVideo"
    "setupVideoPlayerView"
    "setupView"
    "setupViews"
    "setupWebView"
    "setupWithViewController"
    "shouldUpdateData"
    "shouldUseCachedData"
    "showAlertViewToChooseOnePicInResultPics"
    "showAlertWithTitleAndButton"
    "showBottomSheet"
    "showCanInteraction"
    "showChoosePicAleat"
    "showDownLoadAlert"
    "showDownLoadProgressView"
    "showDrewPicView"
    "showEditBottomView"
    "showErrorAlert"
    "showFallbackBackground"
    "showGifAnimation"
    "showGoodReputationView"
    "showImagePicker"
    "showLoading"
    "showMemoryLimitAlert"
    "showModelSelection"
    "showNetErrorToast"
    "showNoFreeMemorySpaceAlert"
    "showNoInteraction"
    "showNoNetWorkConnectAlert"
    "showResultEditView"
    "showRusultPicsInBottomView"
    "showSelectButton"
    "showToast"
    "shuffle"
    "signWithParameters"
    "splitKeywordPair"
    "splitKeywordPairDelFirst"
    "startBottomSheetAnimationImageView"
    "startCellularDataNotifier"
    "startCheck"
    "startDataTimer"
    "startEraseAndRestoreEffect"
    "startFloatingButtonRotation"
    "startListenDownloadModelCompletedNoti"
    "startLoadingBackgroundImage"
    "startLoadingImage"
    "startLongDataTimer"
    "startProgressPolling"
    "startReachabilityNotifier"
    "startReverseEraseAnimation"
    "startStripeAnimation"
    "startgeneratePic"
    "stopAndClean"
    "stopDataTimer"
    "stopFloatingButtonRotation"
    "stopFooterRefreshing"
    "stopFooterRefreshingWithNoMoreData"
    "stopHeaderRefreshing"
    "stopHeaderRefreshingWithNoMoreData"
    "stopLastVideoPlayer"
    "stopLongDataTimer"
    "stopProgressPolling"
    "stopReconnection"
    "stopRefreshingWithNoMoreData"
    "stopRotating"
    "stopTimer"
    "stopVideo"
    "subscribeVC"
    "switchChildViewController"
    "switchViewController"
    "templateChildVC"
    "textWidth"
    "toAlamofireMethod"
    "toRawBytes"
    "toRecognizedObject"
    "toggleModelOptions"
    "togglePlayPause"
    "toggleRightButton"
    "topMostViewController"
    "transformCoords"
    "unzipFile"
    "updateAccessibility"
    "updateAppConfigWithVipData"
    "updateBackgroundAppearance"
    "updateBannerImages"
    "updateBrushSizeLabelConstraintsWithIsHidden"
    "updateButtonAppearance"
    "updateButtonGradient"
    "updateCache"
    "updateCharacterCount"
    "updateCloseBtnStatu"
    "updateConfig"
    "updateCornerRadius"
    "updateDottedLine"
    "updateEditViewUI"
    "updateGestureRecognizers"
    "updateGradientDirection"
    "updateGradientLayer"
    "updateGradientLayerFrame"
    "updateHDButtonState"
    "updateHeight"
    "updateImage"
    "updateImageURLs"
    "updateImageUrls"
    "updateImageViewFrame"
    "updateImages"
    "updateItemsAndUrls"
    "updateLocalUserInfo"
    "updateModeUI"
    "updateModelSelectView"
    "updateNaviTitle"
    "updatePageControl"
    "updatePageNumberLabel"
    "updatePagination"
    "updateParametersDisplay"
    "updatePhotoAndVideoSegmentButtonsState"
    "updatePlaceholderVisibility"
    "updatePlaceholders"
    "updatePlayerLayerFrame"
    "updateProgress"
    "updatePromptCount"
    "updatePromptTextViewWithInputText"
    "updateRemainingTimes"
    "updateScrollViewHeight"
    "updateScrollViewState"
    "updateSegmentAppearance"
    "updateSegmentButtonsState"
    "updateSegmentControlAndChildViewControllers"
    "updateSelectedNumber"
    "updateSelection"
    "updateSelectionLabel"
    "updateSelectionState"
    "updateStartButtonState"
    "updateStatus"
    "updateStripePattern"
    "updateSubmitButtonState"
    "updateSubscriptionOptions"
    "updateTopLabel"
    "updateUI"
    "updateUIForSuccessfulGeneration"
    "updateUIInfo"
    "updateUIWithItemData"
    "updateUserCount"
    "updateVideoModels"
    "updateVideoProgress"
    "updateYoloButtonsState"
    "updateZPositions"
    "uploadImage"
    "uploadOriginalImages"
    "uploadPic"
    "uploadPicWithImageAndType"
    "validateInput"
    "videoGotoGenerateVC"
    "videoUploadPicWithImageAndType"
    "viewControllerForImage"
    "viewForZooming"
    "waitUntilDone"
    "withAlpha"
    "writePNG"
    "yoloGetReconizeFromPic"
    "yoloUpdateLabelButtons"
)

# # 属性名数组 (2186个)
SWIFT_PROPERTIES=(
    "AIClickOfflineediting"
    "AIDressup"
    "AIKiss"
    "AIMagicVideo"
    "AIMagicVideoUploadYourPhotoInstantlyCreateMagicalAIVideos"
    "AIQuick"
    "AIRecognize"
    "AIRecognizeOfflineediting"
    "AIStarting"
    "AIVideo"
    "AIVideoButton"
    "Add1DuoPhoto"
    "AddPerson1"
    "AddPerson2"
    "AddSingleorDuoPhoto"
    "AfterexitingtheimageisstillbeinggeneratedPleasechecktheresultpage"
    "AfterexitingthevideoisstillbeinggeneratedPleasechecktheresultpage"
    "AivideoButton"
    "AivideoL"
    "AllFeaturesUnlocked"
    "AllTemplates"
    "Analyzingtheimage"
    "Areyousuretodeletetheselectitems"
    "Availableforfreebuttheimagegenerationspeedisslower"
    "Back"
    "BadeffectPleasetryuploadingotherphoto"
    "Beingsaved"
    "BlushButtonImageView"
    "BlushButtonLabel"
    "BlushContainerView"
    "Brieflydescribetheobjectsyouwanttochange"
    "Brieflydescribetheobjectsyouwanttokeep"
    "Brush"
    "Brushovertheimageobjectyouwishtomodify"
    "Brushtheobjectinthephototomodifyit"
    "Cancelall"
    "Centerthepersonforbetterresults"
    "ChangeclothesBGfirst"
    "Changeobjectsbyinputtext"
    "Changeselectedobjectto"
    "Choosetheproblemyouencountered"
    "Claim"
    "Claimed"
    "Claimsucceed"
    "Click"
    "Clickobjectinthephoto"
    "Clickonanobjectintheimageinputthedesiredeffectandgenerate"
    "Cloud"
    "Confirm"
    "Confirmselection"
    "Contact"
    "ContactUs"
    "ContentGenerationFailed"
    "Continue"
    "CreateAIVideo"
    "Creation"
    "Creativedescription"
    "CroppingtheimagewillclearthecurrentdrawncontentPleaseconfirm"
    "Currentlythereisnoaccesstothecamera"
    "Currentlythereisnoalbumaccess"
    "DYAccountSecTokenKey"
    "DYBuyDiamondClose"
    "DYBuyDiamondFailed"
    "DYBuyDiamondPresent"
    "DYBuyDiamondSuccess"
    "DYDownLoadModelWaitGoToOnlinePage"
    "DYDrawNoWhatIWantClickCancel"
    "DYDrawNoWhatIWantClickSubmit"
    "DYDrawSaveClick"
    "DYHomeAiClickHomeSubscribeClick"
    "DYHomeAiClickOnLineAiDressupClick"
    "DYHomeAiClickOnLineFreestyleClick"
    "DYHomeAiClickOnLineMagicBlushClick"
    "DYHomeAiPhototoVideoClick"
    "DYHomeAiPhototoVideoClickGotoBuyDiamond"
    "DYHomeAiPhototoVideoNoDiamond"
    "DYHomeAiTexttoVideoClick"
    "DYHomeAiTexttoVideoClickGotoBuyDiamond"
    "DYHomeAiTexttoVideoNoDiamond"
    "DYHomeAiVideoClick"
    "DYHomeAiVideoClickGotoBuyDiamond"
    "DYHomeAiVideoNoDiamondClick"
    "DYHomeClickVipGoToSubscribe"
    "DYHomeOfflineEditorClick"
    "DYHomeShowPicTime"
    "DYHomeShowVideoTime"
    "DYHomeSwiperClick"
    "DYInterPageToOnlinePage"
    "DYKissInterShowTipView"
    "DYKissVideoCreate"
    "DYKissVideoCreateFailed"
    "DYKissVideoCreateSuccess"
    "DYKissVideoNoDiamond"
    "DYPicPreviewClickAIDressUp"
    "DYPicPreviewClickaivideo"
    "DYPicResultClickaivideo"
    "DYProVipStatusTip"
    "DYSignKey"
    "DYUserVideoPoint"
    "DYVideoGenerateClickContinue"
    "DYVipStatusTip"
    "DYXuanfuEnableKey"
    "DYmdAiDrawupNoCountToBuy"
    "DYmdBuyCountPageCancel"
    "DYmdBuyCountPageFail"
    "DYmdBuyCountPageSuccess"
    "DYmdBuyPageCancel"
    "DYmdBuyPageClose"
    "DYmdBuyPageFail"
    "DYmdBuyPageGetOrdersFail"
    "DYmdBuyPageOpen"
    "DYmdBuyPageSuccess"
    "DYmdDownloadClick"
    "DYmdDownloadFail"
    "DYmdDownloadSuccess"
    "DYmdDrawGeneratePageNoCountToBuy"
    "DYmdDrawNoCountToBuyCancel"
    "DYmdDrawNoCountToBuyClose"
    "DYmdDrawNoCountToBuyOpen"
    "DYmdDrawNoCountToBuySuccess"
    "DYmdDrawingEnterForeground"
    "DYmdDrawingSlowToOnlinePage"
    "DYmdDrawingTurnToBackground"
    "DYmdLocalDrawingEnterForeground"
    "DYmdLocalDrawingTurnToBackground"
    "DYmdNOVipNoCountToBuyCount"
    "DYmdNOVipNoHDCountToBuyCount"
    "DYmdPicDrawingTurnToBackground"
    "DYmdVideoDrawingTurnToBackground"
    "DYmdVipNoCountToBuyCount"
    "DYmdVipNoHDCountToBuyCount"
    "DYmdfreestyleNoCountToBuy"
    "DYmdmagicbrushDrawNoCountToBuy"
    "Describethetransformationyouwantswimsuit"
    "Describethetransformationyouwanttomake"
    "Describethetransformationyouwanttomakebaseballuniform"
    "Describeyourissue"
    "DescriptionOptimize"
    "Details"
    "Diamonds"
    "DiamondsforAIVideo"
    "Dontshowagain"
    "Download"
    "DownloadAIprogramtoiPhone"
    "DownloadFailure"
    "DownloadFailureCompensation"
    "Downloading"
    "DownloadingisinprogressIfyouexitnowitwillrequireyoutodownloaditagain"
    "Downloadingthemodel"
    "Downloadmodel"
    "Downloadthemodel"
    "Edit"
    "Egreddressmuscle"
    "Enteremailaddress"
    "Enterprompt"
    "Enterpromptforselectionarea"
    "EnterreplacedPhoto"
    "Enterwantedkeepobjects"
    "Enterwantedreplaceobjects"
    "Eraser"
    "Exitingtheappinthebackgroundduringphotogeneration"
    "Failedtodownloadimage"
    "Failedtogeneratepleasetryagainlater"
    "Failedtosavepicture"
    "FastGeneration"
    "Fasterprocessing"
    "Fastgenerate"
    "Floatingwindow"
    "Freestyle"
    "Freestyleoutfitchangesbyselectingkeywords"
    "FreetoUse"
    "Fulleffect"
    "GeneratedLength"
    "GeneratedwithAl"
    "Generation"
    "GenerationisrestrictedYoucandisconnectfromthenetworkorenableairplanemodetoproceed"
    "GenerationisrestrictedYoucandownloadthelocalmodeltogetmorefunctions"
    "GetMoreTimes"
    "Getmoretimes"
    "Getpackageinformation"
    "Getpackageinformationfailed"
    "Gotit"
    "Gotodraw"
    "GotosystemSettings"
    "HDupto2k"
    "HelpFeedback"
    "Identifying"
    "Identifytheobjectintheimageandselectenterthedesiredeffectgenerate"
    "Imagebeinggenerated"
    "Instantprocessing"
    "Insuffcientdiamondbalance"
    "InvalidEmailFormat"
    "InvalidURL"
    "ItsbeingdownloadedPleasewaitamoment"
    "JPUSH_APP_KEY"
    "JPUSH_CHANNEL"
    "Keywordcheckfailedpleasetryagain"
    "Keywordviolationpleasereenter"
    "LLNetworkStateChangedNotification"
    "Letschooseamodel"
    "LocalDrawSensitiveShowRemindUserCloseNet"
    "LocalProcessing"
    "MZRefreshDateKey"
    "MZRefreshFooterKey"
    "MZRefreshFooterTag"
    "MZRefreshHeaderIsRefreshingKey"
    "MZRefreshHeaderKey"
    "MZRefreshHeaderOffsetKey"
    "MZRefreshHeaderTag"
    "MZRefreshIsNoMoreDataKey"
    "MZRefreshNoMoreDataFooterKey"
    "MZRefreshScreenWidth"
    "MZRefreshStatusColorChanged"
    "MZRefreshStatusFontChanged"
    "MZRefreshTimeColorChanged"
    "MZRefreshTimeFontChanged"
    "MagicBrush"
    "Magicbrush"
    "MagicbrushOfflineediting"
    "Modeldownloadfailure"
    "Modelselection"
    "Modelsize"
    "Modify"
    "Morediamonds"
    "Moretimes"
    "Moretimestxt"
    "MoretimestxtWidth"
    "Morevideotemplates"
    "My_works"
    "Networkbusymodeldownloadfailedpleasedownloadagain"
    "Noadvertisements"
    "NointernetconnectionPleaseconnecttocontinue"
    "Nomessagesfornow"
    "NotrecognizedPleaseusetheBrushtool"
    "Offline"
    "OfflineEditing"
    "OfflineEditor"
    "OfflineFreedom"
    "OfflineslowUseonlineforspeed"
    "OneTapOutfitChangeGeneratethestyleyouwantwithoneclick"
    "Online"
    "OnlineEditing"
    "Optimize"
    "Partialeffect"
    "Photoalbum"
    "Photosupportsmoving"
    "Photosupportszooming"
    "Phototovideo"
    "Pictureisempty"
    "PleaseClicktheobjectyouwanttoreplace"
    "PleaseEnterprompt"
    "PleaseallowaccesstoyourphotolibraryinSettings"
    "Pleasedescribethevideoeffectyouneedtogenerate"
    "Pleasedownloadthemodelfirst"
    "Pleasedrawselection"
    "Pleasedrawtheareathatneedstobeedited"
    "Pleaseenteracontactemailaddress"
    "Pleaseenterthedesireddrawingcontent"
    "Pleaseenterthetextualdescription"
    "Pleaseenteryourcontactemail"
    "Pleaseselectatleastonepicture"
    "Pleaseselectreplaceobject"
    "Pleaseselectthedesiredreplacementeffect"
    "Pleaseselectthetemplate"
    "Pleaseuploadaportraitphoto"
    "Pleaseuploadpicture"
    "Pleaseuploadtwophotoswithportrait"
    "PleasewaitYoucurrentlyhaveataskbeingcarriedout"
    "Pleasewaitthemodelisdownloading"
    "Pleasewaitwhiletheimageisbeingcomposited"
    "PrivacyPolicyUrl"
    "Privacypolicy"
    "PrivatetoYouOnly"
    "Promptwordisrestricted"
    "Provideascreenshotoftheproblem"
    "QuickButton"
    "QuickButtonImageView"
    "QuickButtonLabel"
    "QuickContainerView"
    "QuickStartTip"
    "QuickStartTipIsShow"
    "QuickTipImg"
    "QuickTipLabel"
    "RamdonGenerateFunctionItems"
    "RamdonGeneratePicSecondLevelData"
    "RandomGeneration"
    "RandomText"
    "Randomoutfitsnomoredecisionfatigue"
    "Rangeofmotion"
    "Recognizetheobjectsintheimageselectoneormoreinputthedesiredeffectandgenerate"
    "RemainingDiamonds"
    "RemainingGenerationTimesToday"
    "RenewsautomaticallyCancelanytime"
    "SavedtoalbumFailed"
    "Savedtoalbumsuccessfully"
    "Selectall"
    "Selectpicturemode"
    "Selectreplaceobjects"
    "Selecttherecognizedobjecttomodify"
    "Selectyourphotostyle"
    "Settings"
    "SingleModelDownloadButton"
    "SingleorDuoPhoto"
    "Smartfacechangingstartyourwonderfuljourneyoffacechanging"
    "Start"
    "Stylisticshifts"
    "SubForAIPhoto"
    "SubforAIVideoAIPhoto"
    "SubforAIVideoAIPhotoTxt"
    "SubforAIVideoAIPhotoTxtWidth"
    "SubmissionfailedPleasetryagain"
    "Submissionsuccessful"
    "Submitsuccessfully"
    "Subscribetounlockallfeatures"
    "Subscribetounlockfeatures"
    "Supporteddevices"
    "SwitchingwillendthegenerationDoyouwanttoswitch"
    "TermsofUseUrl"
    "Termsofuse"
    "Texthasbeencopiedtotheclipboard"
    "Texttoimage"
    "Texttovideo"
    "TheXawaappisdesignedexclusively"
    "Thecurrenttemplateistemporarilyunavailable"
    "Thedeletedprojectcontentcannotberestored"
    "Thefreememoryspaceofthephoneis"
    "Theimagegenerationspeedisfastandtheresultsareexcellent"
    "ThemodelisdownloadingYoucanuseonlinefeaturesmeanwhile"
    "ThemodelneedstobedownloadedviatheInternet"
    "ThenetworkisbusyandthemodeldownloadhasfailedWehaveadded50Timespacks"
    "Thephotowillbeprocessedsoondoyouwanttoexit"
    "ThephotowillbeprocessedsoondoyouwanttoexitWewillnotifyyou"
    "Thereareimagesbeinggenerated"
    "TherelevantobjectwasnotrecognizedPleasechangethepictureortryagainlater"
    "Therequestedcontentcouldntbegeneratedonline"
    "Thesizeofthemodelis18Gdownloaditnow"
    "Thesystemisbusypleasetryagainlater"
    "ThevideofailedtoplayPleasetryagainlater"
    "TimesforAIPhoto"
    "TodayFreeviewingADusehasendedyouneedtoopenamembershiptocontinueusing"
    "TodayfreetimeshavebeenusedupyoucanuseortopuptheVIPbywatchingtheadvertisement"
    "TodaysfreeADviewingusagehasendedYouneedtopurchaseanumberoftimestocontinueusingit"
    "Todayviptimeshavebeenusedupyoucanuseorbuymoretimesbywatchingtheadvertisement"
    "TryPRONow"
    "TrySubscribeNow"
    "Tryagain"
    "Turnon"
    "Turnonnotificationsandwait2minutesforthemagicresult"
    "Turnonnotificationswellnotifyyouwhenitsready"
    "Unabletoaccessalbums"
    "Unabletoaccesscamera"
    "UnlockVIPFeatures"
    "UnlockVIPFeaturestxt"
    "UnlockVIPFeaturestxtWidth"
    "Unlockallfunction"
    "Unlockallfunctions"
    "Unzippingpleasewait"
    "UploadFirstPerson"
    "UploadSecondPerson"
    "UploadanHDphotowithyourfacevisible"
    "Uploadaphoto"
    "UploadlssueScreenshot"
    "UseItButton"
    "Usethistemplate"
    "VideoClarity"
    "VideoisgeneratingaboutaminuteYoucancontinuetogenerateothervideos"
    "Waitaminute"
    "Waityouhavephotobeinggenerated"
    "Watchadvertisements"
    "WeDontKeepYourData"
    "Whethertoconfirmthedeletion"
    "XawaAppCompatibility"
    "YOLOv8Model"
    "Youcanturnoffthenetworkorenableairplanemodeandtryagain"
    "Youcanusethedrawingtoolwhileyourvideoisbeinggenerated"
    "Youdidnhaveworks"
    "Youhavealreadyclaimedit"
    "Youhavenotenabledthemessagenotification"
    "Yourdailynumberhasbeenusedup"
    "Yourfeedbackhelpsusimprove"
    "Yourmodelisready"
    "ZoomMovePhoto"
#    "accelerationFactor"
#    "accountSecToken"
#    "actionButton"
#    "activeColor"
#    "activeContentbrJtmJjbtAuwG"
#    "activeHeight"
#    "activeLayer"
#    "activeLayerX"
#    "activeResultktkimqil"
#    "activeTokenIJnqO"
#    "activeWidth"
#    "activityIndicator"
#    "actualDiameter"
#    "actualIndex"
#    "actualIndicatorSize"
#    "addheight"
#    "addr"
#    "addrFamily"
#    "adjustedEraserRadius"
#    "aiDressUpButton"
#    "alertContainerHeight"
#    "alertType"
#    "allChildVC"
#    "allData"
#    "allFunctionItems"
#    "allImageNames"
#    "allImageUrls"
#    "allSection"
#    "allSections"
#    "allSelectedPrompts"
#    "allVideoData"
#    "allfunctiontxt"
#    "allfunctiontxtWidth"
#    "andRandomArr"
#    "animatedView"
#    "animatedViewX"
#    "animationBlock"
#    "animationDelay"
#    "animationGroup"
#    "animationGroup1"
#    "animationGroup2"
#    "animationOptions"
#    "animationPicsArr"
#    "animationWidth"
#    "apiTimeout"
#    "appStoreID"
#    "appUpdateAppstoreId"
#    "appUrl"
#    "appname"
#    "argmax"
#    "arrowButton"
#    "arrowImageView"
#    "asNative"
#    "attributedMessage"
#    "autoDismissOnConfirm"
#    "autoFullscreen"
#    "availableCount"
#    "avatarImageView"
#    "bDiff"
#    "bTitleLabel"
#    "backAction"
#    "backBarButtonItem"
#    "backBtn"
#    "backButton"
#    "backImage"
#    "backMaskView"
#    "backgroundImageView"
#    "backgroundLayer"
#    "backgroundSessionCompletionHandler"
#    "backgroundTask"
#    "bannerImages"
#    "bannerView"
#    "baseHeightForSection0"
#    "beginRefresh"
#    "bgImageView"
#    "bgLayer1"
#    "bgView"
#    "bg_p1imageView"
#    "bg_p2imageView"
#    "bg_p3imageView"
#    "blurView"
#    "blushButton"
#    "boldFont"
#    "boldRanges"
#    "bonjourBrowser"
#    "borderResetWorkItem"
#    "borderW"
#    "bottomBtnsView"
#    "bottomGradualBgView"
#    "bottomHeight"
#    "bottomIMGV"
#    "bottomPadding"
#    "bottomSafeAreaHeight"
#    "bottomSheetAnimationImageView"
#    "bottomSheetButtonStackView"
#    "bottomSheetCloseBtn"
#    "bottomSheetContentView"
#    "bottomSheetHeight"
#    "bottomSheetOverlayView"
#    "bottomSheetSaveBtn"
#    "bottomSheetScrollView"
#    "bottomSheetTipCloseButton"
#    "bottomSheetTipContainerView"
#    "bottomSheetTipIconImageView"
#    "bottomSheetTipLabel"
#    "bottomSheetView"
#    "bottomSheetViewOringleImageView"
#    "bottomSheetViewProgreenLabel"
#    "bottomSheetViewProgreenSlider"
#    "bottomSheetViewResultImageTipLabel1"
#    "bottomSheetViewResultImageTipLabel2"
#    "bottomSheetViewResultImageView"
#    "bottomSheetViewResultImageView1"
#    "bottomToTabBarTopDistance"
#    "bottomViewChooseNumber"
#    "bottomViewChooseNumberIsVip"
#    "bottomViewHeight"
#    "bottomViewIsSelectHD"
#    "boundingBoxTool"
#    "boxEnd"
#    "brushSizeLabel"
#    "brushSizeLabelIsHidden"
#    "brushSizeLabelTextWidth"
#    "brushSizeSlider"
#    "btnCorner"
#    "btnEndColor"
#    "btnNormalBgColor"
#    "btnStartColor"
#    "btnheight"
#    "buttonContainer"
#    "buttonContainerView"
#    "buttonCooldown"
#    "buttonCount"
#    "buttonFrame"
#    "buttonHeight"
#    "buttonOne"
#    "buttonPosition"
#    "buttonScrollView"
#    "buttonSize"
#    "buttonSpacing"
#    "buttonStack"
#    "buttonStackView"
#    "buttonTwo"
#    "buttonWidth"
#    "cStride"
#    "cacheData"
#    "cacheExpirationInterval"
#    "cacheSectionsKey"
#    "cachedAllImageUrls"
#    "cachedCloudData"
#    "cachedConfigIiyxZH"
#    "cachedFilteredPackages"
#    "cachedId"
#    "cachedImageEncoding"
#    "cachedImages"
#    "cachedImg"
#    "cachedJsonData"
#    "cachedModels"
#    "cachedPrices"
#    "cachedTime"
#    "cachedVideoURLs"
#    "cachedVipconfData"
#    "canConnectAutomatically"
#    "canConnectWithoutUserInteraction"
#    "canSwitchPage"
#    "cancelAllText"
#    "cancelAllWidth"
#    "cancelButton"
#    "cancellable"
#    "cancellables"
#    "candidateColors"
#    "cardFlipView"
#    "cellArea"
#    "cellFrame"
#    "cellHeightCache"
#    "cellularData"
#    "changeModelButton"
#    "changeModelButtonWidth"
#    "changeclothesBGfirstView"
#    "changeclothesBGfirstViewcheckIMG"
#    "channelAxis"
#    "channelDim"
#    "channelOffset"
#    "channelStride"
#    "chars"
#    "checkImageView"
#    "checking"
#    "checkingWithBecomeActive"
#    "chooseModelButton"
#    "ciContext"
#    "circleView"
#    "cleanedBase64String"
#    "cleanedString"
#    "clearButton"
#    "clickAIDressupBtnCompletion"
#    "clickAIVideoBtnCompletion"
#    "clickCloseBtnBlo"
#    "clock"
#    "closeAlertEnable"
#    "closeBtn"
#    "closeButton"
#    "cloudOrLocalSegmentSelectIndex"
#    "cloudPhotoCurrentPage"
#    "cloudPhotoData"
#    "cloudPhotoTotalNum"
#    "cloudPhotoTotalPage"
#    "cloudVideoCurrentPage"
#    "cloudVideoData"
#    "cloudVideoTotalNum"
#    "cloudVideoTotalPage"
#    "colorImage"
#    "colorSet"
#    "columnSpacing"
#    "compareReceivedMsgId"
#    "compiledURL"
#    "completedCount"
#    "compressedImage"
#    "compression"
#    "confirmButton"
#    "connectionTimeout"
#    "containerSize"
#    "containerView"
#    "containnerBundle"
#    "contentAlignment"
#    "contentHeightDidChange"
#    "contentLabel"
#    "contentScrollView"
#    "contentViewHeight"
#    "contentWidth"
#    "continueButton"
#    "continueButtonWidth"
#    "controlsContainer"
#    "cornerPosition"
#    "countTitle"
#    "coverBgImageView"
#    "coverImage"
#    "coverMoveImageView"
#    "coverMoveImageView1"
#    "coverV"
#    "createCoverView"
#    "createL"
#    "createModelParamsSaveKey"
#    "createVideoButtonH"
#    "creationButton"
#    "croppedImage"
#    "croppedLeftImage"
#    "croppedRightImage"
#    "currentAlertView"
#    "currentChar"
#    "currentCollectionViewType"
#    "currentCreatingArr"
#    "currentDurationIndex"
#    "currentEnvironment"
#    "currentHandlerKoLRdq"
#    "currentHandlerSQiIntFNayBiG"
#    "currentImageHash"
#    "currentImageIndex"
#    "currentImageUploadSuccessUrl"
#    "currentImageUploadUrl"
#    "currentImageUrl"
#    "currentImageView"
#    "currentIsInAiDressOrFreeStyle"
#    "currentLanguage"
#    "currentLevelData"
#    "currentLocale"
#    "currentMinutes"
#    "currentModelIndex"
#    "currentModelKey"
#    "currentModelLabel"
#    "currentMotionIndex"
#    "currentNeedPrice"
#    "currentNode"
#    "currentProgress"
#    "currentQualityIndex"
#    "currentReconnectAttempt"
#    "currentRetryCount"
#    "currentScaledPoint"
#    "currentScrollView"
#    "currentSeconds"
#    "currentSecondsRemainder"
#    "currentSection"
#    "currentSegmentIndex"
#    "currentSelectImageIndex"
#    "currentSelectIndex"
#    "currentSelectModelItemView"
#    "currentState"
#    "currentStatus"
#    "currentStyleIndex"
#    "currentText"
#    "currentTimestamp"
#    "currentUrl"
#    "currentVC"
#    "currentVNeedPoint"
#    "currentValueBhAdRGnEzGX"
#    "currentValueFmuuKAYOIpT"
#    "currentValuebmYDGPqUKiG"
#    "currentValueixlUNBWlbKz"
#    "currentValuepcjGBfdiiLs"
#    "currentValuetpAtUGjgmOz"
#    "currentValuexJigYNdVbxC"
#    "currentVseconds"
#    "currentWebUrl"
#    "currentWidth"
#    "customAlertController"
#    "customSegmentControl"
#    "custonImageName"
#    "cutImg"
#    "dYHomeVC"
#    "dataManager"
#    "dataString"
#    "dataView"
#    "dataWithImageNameInDocment"
#    "dataWithImageUrls"
#    "dataWithImages"
#    "dateAdded"
#    "dayTimesSaveTip"
#    "daytimes"
#    "dealUI"
#    "dealvc"
#    "decelerationFactor"
#    "decodedData"
#    "defaultCachedoIpwrRwI"
#    "defaultColor"
#    "defaultConfig"
#    "defaultHeightRatio"
#    "defaultImages"
#    "defaultInfoYAvpWyjqJzsL"
#    "defaultScrollViewMaxHeight"
#    "defaultSelectedIndex"
#    "defaultSelectedSubscriptionIndex"
#    "defaultSelectedValue"
#    "defaultStateShjMsFZUeM"
#    "delButton"
#    "deleteButton"
#    "deleteUrlCompletion"
#    "deletedpicturesSuccessfully"
#    "desLabel1"
#    "descLabel"
#    "descriptionContainerViewH"
#    "descriptionLabel"
#    "descriptionLabels"
#    "descriptionTextView"
#    "descriptionTitleLabel"
#    "descriptions"
#    "destBuffer"
#    "destBytesPerRow"
#    "destRowBytes"
#    "deviceMap"
#    "diamondButton"
#    "diamondBuyVC"
#    "diamondImageView"
#    "diamondLabel"
#    "diamondMp4Urls"
#    "diamondNoHaveButton"
#    "diamondTip"
#    "diamondTipStr"
#    "diamondTitleStr"
#    "diamondsCountLabel"
#    "diamondtipLabel"
#    "didTapPlayButtonCallback"
#    "didTapSelectButtonCallback"
#    "didTapSubView"
#    "didTapUseItButtonCallback"
#    "differenceArr"
#    "digest"
#    "discountLabel"
#    "dismissCompletion"
#    "displayDuration"
#    "displayLink"
#    "displayNumber"
#    "distance"
#    "distanceFromBottom"
#    "doneButton"
#    "dotConfig"
#    "doubleTapGesture"
#    "downBtn"
#    "downLoadCancellables"
#    "downloadAlertView"
#    "downloadBtnHidden"
#    "downloadButton"
#    "downloadModelProgressView"
#    "downloadSubscriber"
#    "downloadTasks"
#    "downloadedURL"
#    "dps_state"
#    "drawBottomView"
#    "drawBtn"
#    "drawBtnsWidth"
#    "drawCurrentSelectImage"
#    "drawFreestyleInputString"
#    "drawFreestyleOutputString"
#    "drawGenerateContainerView"
#    "drawGenerateimageView"
#    "drawH"
#    "drawHistoryDataList"
#    "drawLast"
#    "drawMode"
#    "drawPicCanBackStepCount"
#    "drawPicOn512PicRect"
#    "drawSelectPicIndex"
#    "drawToolsView"
#    "drawVCIndex"
#    "dressResultConfirmButton"
#    "dressResultPicsAleartView"
#    "dressResultPicsMaskView"
#    "dressResultbuttonScrollView"
#    "dressResultmainImageView"
#    "drewPicLeftSelectPicButton"
#    "drewPicRightSelectPicButton"
#    "dummyData"
#    "durationConfig"
#    "dyDownloadModelCompletedNoti"
#    "dychildViewControllers"
#    "dychoosePicType"
#    "dynamicDurationButtons"
#    "dynamicModelButtons"
#    "dynamicMotionButtons"
#    "dynamicQualityButtons"
#    "dynamicStyleButtons"
#    "editBtnsView"
#    "emailPredicate"
#    "emailRegex"
#    "emailTextField"
#    "emailTitleLabel"
#    "emptyIMG"
#    "emptyImageView"
#    "emptyTipLabel"
#    "emptyView"
#    "encodingStart"
#    "encryptedStateuEkbaPFcXHwQv"
#    "encryptedTokendCFYpIUJgU"
#    "encryptedTokengOqVZtzH"
#    "endColor"
#    "endImagePoint"
#    "endTime"
#    "enterType"
#    "enterTypes"
#    "eraserButton"
#    "eraserButtonImageView"
#    "eraserButtonLabel"
#    "eraserContainerView"
#    "eraserImageHistoryArr"
#    "eraserRadius"
#    "erasureLastMaskImageView"
#    "errorMsg"
#    "errorView"
#    "existingViewCount"
#    "expectedContentWidth"
#    "exportURL"
#    "fadeView"
#    "failSize"
#    "failedCount"
#    "failedtouploadpicture"
#    "failureCount"
#    "feats0"
#    "feats1"
#    "featureStackView"
#    "featureView"
#    "feedVC"
#    "fetchedProducts"
#    "fileSizes"
#    "filtered"
#    "filteredArray"
#    "filteredPackages"
#    "finalArr"
#    "finalCgImage"
#    "finalDescript"
#    "finalFrame"
#    "finalMaskImageView"
#    "finalMp4Url"
#    "finalParams"
#    "finalRect"
#    "finalSize"
#    "finalUrl"
#    "finderSortArray"
#    "finderSortBlock"
#    "firstAppearance"
#    "firstCached"
#    "firstImageUrl"
#    "firstLabel"
#    "firstLevelItems"
#    "firstLevelStringData"
#    "firstNav"
#    "firstRunFlag"
#    "firstSelectKey"
#    "firstSelectL"
#    "firstStr"
#    "fivePicTopTipLabel"
#    "flippedImage"
#    "flippedY"
#    "floatScores"
#    "floatingButton"
#    "folderSize"
#    "fontSizeWithbold"
#    "footer"
#    "frameDuration"
#    "frameX"
#    "freestyleButton"
#    "fromResultVCShowEditBtnsView"
#    "fullRange"
#    "fullscreenButton"
#    "functionItems"
#    "gDiff"
#    "genIcon"
#    "generatePageSensitiveShowRemindUser"
#    "generatePicAndSendState"
#    "generatePicCount"
#    "generateTotalTime"
#    "generatingLabel"
#    "generationLabel"
#    "generator"
#    "gifImageView"
#    "gifInfo"
#    "gifPlaceholder"
#    "gifProperties"
#    "gifView"
#    "globalHandleruZlsqfns"
#    "globalInfoiDUBDvLtAuJHQ"
#    "globalObjectLDHEJOdrxzD"
#    "globalObjectPvEyFyHNiRsAe"
#    "globalObjectSgsIQqLGvQY"
#    "globalObjectsARAbzIVShC"
#    "gotoDrawButton"
#    "gradientBackgroundView"
#    "gradientDirection"
#    "greenBuffer"
#    "groupName"
#    "groupedPrompts"
#    "guidanceScale"
#    "handlersQueue"
#    "hasCache"
#    "hasNavigatedToResult"
#    "hasReportedPicLoadTime"
#    "hasUploadedImage"
#    "hdButton"
#    "hdCount"
#    "hdCountLabel"
#    "hdDayTimes"
#    "hdDayTimesSaveTip"
#    "header"
#    "headerView"
#    "heightAxis"
#    "heightRatio"
#    "hiddenImageView"
#    "hidesForSinglePage"
#    "homeSelectHrefFlagString"
#    "homeSelectKeyString"
#    "homeSettingCacheKey"
#    "homeSettingDataArr"
#    "homeVC"
#    "homeVideoIndex"
#    "homeVideoTitle"
#    "homevideoTitle"
#    "horizontalInset"
#    "hostName"
#    "hrefFlag"
#    "hrefFlagArr"
#    "hrefFlagsArr"
#    "i2isArray"
#    "iconArr"
#    "iconImage"
#    "iconImageView"
#    "iconName"
#    "iconView"
#    "idealOffset"
#    "ifaddr"
#    "imageButton"
#    "imageCache"
#    "imageCollectionView"
#    "imageContainerView"
#    "imageCount"
#    "imageCountLabel"
#    "imageEncoderModel"
#    "imageHeight"
#    "imageList"
#    "imageLoadQueue"
#    "imageOffsetY"
#    "imagePreviewVC"
#    "imageRect"
#    "imageStrings"
#    "imageTextToVideoVC"
#    "imageUrls"
#    "imageVC"
#    "imageView1"
#    "imageView2"
#    "imageViewHeight"
#    "imageViewOrVideoTappedBlo"
#    "imageViewPoint"
#    "imageViewSize"
#    "imageViewTappedBlo"
#    "imageViewToAnimate"
#    "imageViewWidth"
#    "imageViewX"
#    "imageViewY"
#    "imageViews"
#    "imageWidth"
#    "imageX"
#    "imageY"
#    "imagesDirectory"
#    "img2video"
#    "imgIsHidden"
#    "imgTop"
#    "imgWidth"
#    "inMemoryCache"
#    "inView"
#    "inactiveColor"
#    "inactiveHeight"
#    "inactiveLayer"
#    "inactiveOriginFrame"
#    "inactiveSize"
#    "inactiveWidth"
#    "indicatorSize"
#    "indicatorView"
#    "initSegmentsToolsViewselectIndex"
#    "initialHeight"
#    "initialImage"
#    "initialPage"
#    "initialPath"
#    "initialSelectedIndex"
#    "inputAndCountAndClearBtnview"
#    "inputSize"
#    "inputStackViewIsShowTitleView"
#    "inputStr"
#    "inputString"
#    "inputTextTipLabel"
#    "inputType"
#    "insetH"
#    "insetV"
#    "instances"
#    "internalTokencIwnvRox"
#    "ipadHeight"
#    "isActiveHollow"
#    "isAnimating"
#    "isAutomaticallyAlert"
#    "isCanLongPress"
#    "isClickOfflineEditorBtn"
#    "isClickPayBtnOrRestoreBtn"
#    "isConfirmButtonEnabled"
#    "isDisabled"
#    "isDownloadingOrUpziping"
#    "isEditingMode"
#    "isEndOfWord"
#    "isFirstLevelLastHaveCustomBtn"
#    "isFromFivePicVC"
#    "isFromHomePush"
#    "isFromKissSelectPic"
#    "isFromLocalDrawVC"
#    "isFromMaterialWithKey"
#    "isFromMyworks"
#    "isFromPicResultPagePushWithPic"
#    "isFromVideoWithKey"
#    "isHDSelected"
#    "isHaveCacheData"
#    "isHaveNetworkConnect"
#    "isHaveShowDrawGif"
#    "isInAiDressOrFreestyle"
#    "isInChangeModel"
#    "isInEraser"
#    "isInRestoreRequest"
#    "isInSelectPic"
#    "isInThirdLevel"
#    "isInactiveHollow"
#    "isKeyboardVisible"
#    "isLastSegment"
#    "isLeftSelected"
#    "isLoadingImage"
#    "isLocalModel"
#    "isLoggingIn"
#    "isLoginPending"
#    "isLooping"
#    "isNeedOnePic"
#    "isNoMoreData"
#    "isObservingStatus"
#    "isOffline"
#    "isOnString"
#    "isPad"
#    "isPerformingPopGesture"
#    "isPhotoSelected"
#    "isPlayerReady"
#    "isPlaying"
#    "isPresentFromVC"
#    "isProduction"
#    "isPushFromPicOrVideo"
#    "isRTL"
#    "isReachable"
#    "isRefreshing"
#    "isReversing"
#    "isSameData"
#    "isScrolling"
#    "isScrollingRight"
#    "isSelect"
#    "isSelectAll"
#    "isSelectedItem"
#    "isShowAdsAleaTView"
#    "isShowDrawView"
#    "isShowGoodCommentView"
#    "isShowPopupView"
#    "isShowTitleView"
#    "isSingleImage"
#    "isTextToVideo"
#    "isTransitioning"
#    "isUserLookAdsComplete"
#    "isUserLookAdsNoHaveCount"
#    "isUsingUrls"
#    "isValid"
#    "isVideoPlayerSetup"
#    "isVip"
#    "isVipButton"
#    "isZoomed"
#    "is_inBackGround"
#    "isfromResultVC"
#    "itemAppearance"
#    "itemHeight"
#    "itemID"
#    "itemImage"
#    "itemView"
#    "itemWidth"
#    "itemsCache"
#    "itemsKey"
#    "jbBtn"
#    "jbButton"
#    "jbImageV"
#    "jpushregistrationID"
#    "jsonData2"
#    "jsonParam"
#    "jsonString1"
#    "jsonString2"
#    "jumpview"
#    "kMinItemHeight"
#    "kMinItemWidth"
#    "keepText"
#    "keepWidth"
#    "keepmode"
#    "keepobjects"
#    "keeptxt"
#    "keyArr"
#    "keyArray"
#    "keyExists"
#    "keyboardHeight"
#    "kissInterpage"
#    "kissInterpageVC"
#    "kissList"
#    "kissListvc"
#    "labelDataArr"
#    "labelFrame"
#    "labelHeight"
#    "labelView"
#    "labelsMultiArray"
#    "languageBundle"
#    "lastClickTime"
#    "lastDataFetchTimeKey"
#    "lastFetchTime"
#    "lastLoginTime"
#    "lastProgress"
#    "lastResultImgsUrlStringArr"
#    "lastScaledPoint"
#    "lastScrollTime"
#    "lastTaskImgUrl"
#    "lastTaskVideoUrl"
#    "lastTime"
#    "lastTouchPoint"
#    "lastUpdate"
#    "lastUpdateTime"
#    "lastVideoPlayer"
#    "lastVideoView"
#    "lastView"
#    "layerFrame"
#    "lbutton"
#    "lbuttonItem"
#    "leftButton"
#    "leftChangePicButton"
#    "leftHeight"
#    "leftIcon"
#    "leftIconImageView"
#    "leftImageTapGesture"
#    "leftImageView"
#    "leftIndex"
#    "leftInset"
#    "leftLayer"
#    "leftOffset"
#    "leftRect"
#    "leftScare"
#    "leftScrollView"
#    "leftSegmentButton"
#    "leftStack"
#    "leftStackView"
#    "leftToRightAnimation"
#    "leftToRightAnimation1"
#    "leftToRightAnimation3"
#    "leftUploadButton"
#    "leftUploadView"
#    
#    "leftWidth"
#    "leftX"
#    "letters"
#    "linkDict"
#    "linkStr"
#    "listenerId"
#    "loadModelProgressBar"
#    "loadedPages"
#    "loading"
#    "loadingIndicator"
#    "loadingView"
#    "localData"
#    "localDowned"
#    "localEditingButtonsStackView"
#    "localHandlerxcykCnQo"
#    "localInfoOzwcvblE"
#    "localItemQbzoBFWi"
#    "localItemaFsarmlb"
#    "localModelDownUrl"
#    "localRecordDownFailed"
#    "logMessage"
#    "logger"
#    "logmsg"
#    "logoIMV"
#    "logoImageView"
#    "logs"
#    "longdataTimer"
#    "lowFeatureMask"
#    "lrMargin"
#    "machineMirror"
#    "magicBrushButton"
#    "maidian"
#    "maidianInfo"
#    "maidianStr"
#    "mainColor"
#    "mainConfigIhTuTDPTUVrsh"
#    "mainConfigJPSZEkqmGHQXC"
#    "mainConfigbTaPhsRBWbWtH"
#    "mainConfigjSWfxoCdPsSKW"
#    "mainConfigmLVWUYGdYDLGb"
#    "mainConfigrANBRqAdswJpF"
#    "mainConfiguhzUldojnRGqA"
#    "mainConfigvIGmofVMtHL"
#    "mainImageView"
#    "mainImageViewH"
#    "mainPeriodLabel"
#    "mainSessionEYRQiNIAnGcR"
#    "manager"
#    "marginHeight"
#    "marginW"
#    "marginWidth"
#    "marginX"
#    "marginyY"
#    "maskAlpha"
#    "maskDecoderModel"
#    "maskImageHistoryList"
#    "maskImageProcessor"
#    "maskImageUploadSuccessUrl"
#    "maskImgUrl"
#    "maskLayer1"
#    "maskLayer2"
#    "maskTapGesture"
#    "maskView1"
#    "maskedImage"
#    "matchedIndex"
#    "matchedObject"
#    "maxCacheSize"
#    "maxDimension"
#    "maxHeight"
#    "maxImageCount"
#    "maxIndicatorSize"
#    "maxInputNumber"
#    "maxMinDistance"
#    "maxProgress"
#    "maxReconnectAttempts"
#    "maxRetryCount"
#    "maxScrollHeight"
#    "maxSize"
#    "maxW"
#    "maybePixelBuffer"
#    "md5Signature"
#    "mdinfo"
#    "memoryCache"
#    "memoryJumpOtherApp"
#    "memoryTip"
#    "memoryTipTxt"
#    "mergedImage"
#    "messageLabel"
#    "messageQueue"
#    "messageQueueLock"
#    "middleColor"
#    "midpoint"
#    "minDistance"
#    "minHeight"
#    "minIndicatorSize"
#    "minLoginInterval"
#    "minimumUpdateInterval"
#    "modelDownloadUrl"
#    "modelFolderName"
#    "modelGenerateImage"
#    "modelIndex"
#    "modelItemViews"
#    "modelLoading"
#    "modelMineZipSize"
#    "modelTipLabel"
#    "modelToggleCurrentModelNamelabel"
#    "modelType"
#    "models"
#    "modelsScrollView"
#    "modifiedDate"
#    "monitor"
#    "monochromeFilter"
#    "motionOptions"
#    "movementConfig"
#    "movementOptions"
#    "movement_amplitude"
#    "mp4CollectionView"
#    "mp4Cover"
#    "mp4Height"
#    "mp4URLString"
#    "mp4url"
#    "mprice"
#    "msgBody"
#    "multiArrayDataType"
#    "mySelf"
#    "nameLabel"
#    "nameWidth"
#    "nameWithoutExtension"
#    "navTitle"
#    "navTitleLabel"
#    "navigationBarBottom"
#    "navigationBarHeight"
#    "needDiamond"
#    "needsConnection"
#    "negativePrompt"
#    "netErrorTip"
#    "netModelUrl"
#    "networkAvailable"
#    "networkListenerId"
#    "networkPlayer"
#    "networkPlayerView"
#    "networkType"
#    "newButton"
#    "newCenterY"
#    "newConnectionStatus"
#    "newDeviceId"
#    "newFrame"
#    "newGifImageView"
#    "newGradientLayer"
#    "newHeight"
#    "newImageHash"
#    "newIndex"
#    "newItems"
#    "newNetworkType"
#    "newPopupX"
#    "newPopupY"
#    "newSection"
#    "newSize"
#    "newTask"
#    "newText"
#    "newTimes"
#    "newWidth"
#    "nextImageView"
#    "nextIndex"
#    "nextLabel"
#    "nextState"
#    "nextTrimmedUrlString"
#    "nextUrl"
#    "nextVideoData"
#    "noCoverImage"
#    "noMoreDataFooter"
#    "noNetAndDownloadModelFailKey"
#    "nonVipButtonIndexes"
#    "normalBackgroundColor"
#    "normalCount"
#    "normalCountLabel"
#    "normalFrame"
#    "normalTextAttributes"
#    "normalTextColor"
#    "normalView"
#    "normalizedString"
#    "normalizedX"
#    "normalizedY"
#    "notificationSettings"
#    "nowTime"
#    "nsRange"
#    "nsText"
#    "nscg"
#    "offlineButton"
#    "offlineButtonTappedBlo"
#    "okAction"
#    "onCardFlipViewImageTapped"
#    "onContinue"
#    "onImageTapped"
#    "onItemClick"
#    "onItemSelected"
#    "onModelSelected"
#    "onNetworkStatusChange"
#    "onOnlineButtonTapped"
#    "onPlaybackFailure"
#    "onPlaybackSuccess"
#    "onReceiveMessage"
#    "onSegmentChanged"
#    "onSwiperTapped"
#    "onUrlEmpty"
#    "oneChangePicButton"
#    "oneDuophoto"
#    "oneImageView"
#    "oneScrollView"
#    "oneUploadButton"
#    "oneUploadContainerView"
#    "onlineButtonsContainer"
#    "onlineEditView"
#    "onlineSubscribeCountVC"
#    "onlineSubscribeCountVCDefauSegmentIndex"
#    "opacityAnimation"
#    "openNotiButton"
#    "operationView"
#    "optionLabel"
#    "optionView"
#    "orderCode"
#    "originArr"
#    "originImageView"
#    "originMp4"
#    "originOffset"
#    "originX"
#    "originalData"
#    "originalImageUploadSuccessUrl"
#    "originalItems"
#    "originalSize"
#    "originalTextViewPosition"
#    "originalTransactionId"
#    "originalViewFrameY"
#    "otherAppUrl"
#    "output"
#    "outputCGImage"
#    "outputScaleX"
#    "outputScaleY"
#    "outputStr"
#    "outputString"
#    "overlayView"
#    "packageList"
#    "packagesFilename"
#    "paddedImage"
#    "paddingView"
#    "pageIndex"
#    "pageIndicatorLabel"
#    "pageNumberLabel"
#    "paramValue"
#    "path1"
#    "path2"
#    "patterns"
#    "payload"
#    "percentageLabel"
#    "phoneMemory"
#    "phoneMemoryLimit"
#    "photoAndVideoSelectedSegmentIndex"
#    "photoButton"
#    "photoText"
#    "photoToVideoButton"
#    "picCollectionView"
#    "picData"
#    "picHeight"
#    "picNumber"
#    "picV"
#    "pipelineLoader"
#    "pixelData"
#    "pixelHeight"
#    "pixelWidth"
#    "pixels"
#    "placeholderImageView"
#    "placeholderLabel"
#    "placeholderPicName"
#    "playButton"
#    "playPauseButton"
#    "playerLayer"
#    "pleasechooseonepictodrew"
#    "plusImageView"
#    "pointTool"
#    "pointsMultiArray"
#    "popup"
#    "popupBackgroundView"
#    "popupBottomY"
#    "popupHeight"
#    "popupMargin"
#    "popupView"
#    "popupX"
#    "popupY"
#    "positivePrompt"
#    "preferredLanguage"
#    "previewImages"
#    "previewScrollView"
#    "previousIndex"
#    "previousState"
#    "priceLabel"
#    "priceLoadingTask"
#    "priceViewPairs"
#    "primaryAction"
#    "primaryButton"
#    "privateHandlercCIOuTYXF"
#    "privateHandlercwZrGSvpH"
#    "privateHandlerrwJGYIDCy"
#    "privateHandleryoiVwAgnq"
#    "privateResultebyvB"
#    "privateSessionmdSyLqVR"
#    "privateTokenOaSHOfWOeusKG"
#    "proDescArr"
#    "proMp4Urls"
#    "proTitle"
#    "proVipStatu"
#    "processStart"
#    "processedMaskImage"
#    "processedOrderCodes"
#    "processedTransactionIDs"
#    "productID1"
#    "progressBar"
#    "progressBarHeight"
#    "progressBarHidden"
#    "progressBarValue"
#    "progressLabel"
#    "progressLayer"
#    "progressObservation"
#    "progressPath"
#    "progressPublisher"
#    "progressSlider"
#    "progressSubject"
#    "progressTimer"
#    "progressView"
#    "progressWidth"
#    "promptClearButton"
#    "promptCountLabel"
#    "promptEncoder"
#    "promptEncoderModel"
#    "promptInputText"
#    "promptInputView"
#    "promptLabel"
#    "promptScrollViews"
#    "promptStackViews"
#    "promptText"
#    "promptTextView"
#    "promptTextViewClearButton"
#    "promptTextViewPlaceHolderColor"
#    "promptTextViewPlaceholderLabel"
#    "provider"
#    "providerData"
#    "ptvInputString"
#    "ptvTopImage"
#    "pulseAnimation"
#    "purpleColor"
#    "purpleText"
#    "query1"
#    "quickAndDrawToolsView"
#    "quickSelectRadius"
#    "rDiff"
#    "randomProptArr"
#    "rcontainerView"
#    "reOptimizeButton"
#    "reachabilityCallBack"
#    "reachabilityRef"
#    "readableSize"
#    "readyAnimation"
#    "readyFrame"
#    "readyGetDayTimes"
#    "readyImage"
#    "readyPushToSubscribeVC"
#    "readyView"
#    "realBannerImages"
#    "reconnectInterval"
#    "reconnectTimer"
#    "rectCardAnimationView"
#    "rectCardAnimationViewTapped"
#    "redDots"
#    "redDotsPoint"
#    "refreshBundle"
#    "refreshFrame"
#    "refreshNormalView"
#    "refreshOffset"
#    "refreshReadyView"
#    "refreshView"
#    "refreshWidth"
#    "refreshingView"
#    "remailDiaCountLabel"
#    "remaining"
#    "remainingTimesView"
#    "remainingWidth"
#    "renewLabel"
#    "replaceObjectsText"
#    "replaceObjectsTextField"
#    "replaceObjectsTitleLabel"
#    "replaceObjectsView"
#    "replaceText"
#    "replaceWidth"
#    "replacedPhoto"
#    "replacedPhotoText"
#    "replacedPhotoTextField"
#    "replacedPhotoTitleLabel"
#    "replacedPhotoView"
#    "replacemode"
#    "replaceobjects"
#    "replacetxt"
#    "requestHeaders"
#    "requestSegmentIndex"
#    "requestSourceType"
#    "resizedIMG"
#    "resizedImage"
#    "resolutionConfig"
#    "resolutionOptions"
#    "restoreButton"
#    "resultCallback"
#    "resultImage"
#    "resultImageCutOn512PicCoverWithDrawPic"
#    "resultImageCutOn512PicNoCover"
#    "resultImageUploadSuccessUrl"
#    "resultImageUploadSuccessUrl2"
#    "resultJsonData"
#    "resultPageFailIndependentDeploymentUrl"
#    "resultPageFailPicTip"
#    "resultPageSensitiveShowRemindUser"
#    "reuploadButton"
#    "rgb1"
#    "rgb2"
#    "rightBarButton"
#    "rightButton"
#    "rightChangePicButton"
#    "rightHeight"
#    "rightImage"
#    "rightImageTapGesture"
#    "rightImageView"
#    "rightIndex"
#    "rightInset"
#    "rightLayer"
#    "rightRect"
#    "rightScare"
#    "rightScrollView"
#    "rightSegmentButton"
#    "rightToLeftAnimation"
#    "rightToLeftAnimation2"
#    "rightToLeftAnimation4"
#    "rightUploadButton"
#    "rightUploadView"
#    
#    "rightWidth"
#    "rightX"
#    "rotitleText"
#    "roundedInterval"
#    "rowStride"
#    "rptitleText"
#    "rtlCol"
#    "saButton"
#    "safeIndex"
#    "saleDesc"
#    "samPoint"
#    "saveButton"
#    "saveErrors"
#    "saveQueue"
#    "saveSemaphore"
#    "savedthepicturesuccess"
#    "savingCount"
#    "scaleHeight"
#    "scaledHeight"
#    "scaledSize"
#    "scaledWidth"
#    "sceneType"
#    "screen_height"
#    "screen_width"
#    "screenshotTitleLabel"
#    "scrollViewSize"
#    "scrollViewWidth"
#    "secondLevelStringData"
#    "secondNav"
#    "secondSelectKey"
#    "secondSelectL"
#    "secondaryAction"
#    "secondaryButton"
#    "sectionModel"
#    "sectionSelectedPrompts"
#    "secureObjectMCOFaW"
#    "secureSessionDfIPDNprWhu"
#    "secureSessionKfhFcIMoiIo"
#    "secureSessionLudPsGrDETmWK"
#    "secureSessionhjccapoRWcE"
#    "secureSessionmXUMxAupRfq"
#    "secureSessionsjWZyTcWUSD"
#    "segmentArr"
#    "segmentControl"
#    "segmentControlView"
#    "segmentDividerLine"
#    "segmentScrollView"
#    "segmentStackView"
#    "segmentViewSelectIndex"
#    "segmentationImages"
#    "segmentationOverlay"
#    "segmentsToolsView"
#    "segmentsToolsViewHieght"
#    "segmentsToolsViewselectIndex"
#    "selectAllButton"
#    "selectAllText"
#    "selectAllWidth"
#    "selectDrawTool"
#    "selectDrawToolHeight"
#    "selectImageButton"
#    "selectKeyString"
#    "selectThreelevelString"
#    "selectTipImage"
#    "selectedBackgroundColor"
#    "selectedBgView"
#    "selectedButton"
#    "selectedCategory"
#    "selectedCount"
#    "selectedData"
#    "selectedDurationText"
#    "selectedHrefFlag"
#    "selectedIDs"
#    "selectedIDsArray"
#    "selectedImageUrl"
#    "selectedImages"
#    "selectedIndexes"
#    "selectedIosPid"
#    "selectedIsVip"
#    "selectedItem"
#    "selectedItems"
#    "selectedKey"
#    "selectedModel"
#    "selectedMotionText"
#    "selectedPoint"
#    "selectedPoints"
#    "selectedQualityText"
#    "selectedStyleText"
#    "selectedSubscriptionTag"
#    "selectedTextAttributes"
#    "selectedThirdLevelItems"
#    "selectedTitle"
#    "selectedValueXIfaBXKLacl"
#    "selectedYoloButtons"
#    "selectedlabel"
#    "selectedvseconds"
#    "selectionLabel"
#    "selfPointer"
#    "semaphore"
#    "semaskLayer2"
#    "sensitiveWords"
#    "setButton"
#    "settingData"
#    "shadowLayer"
#    "sharedCachehSoAGuCRXZkK"
#    "sharedContentpkRTKsygrow"
#    "sharedManagerqaERBYBfTVjK"
#    "sharedNRqWAPd"
#    "sharedProgress"
#    "sharedResultFaxkpVrYUOifln"
#    "sharedResultJsnvEg"
#    "sharedSessionaICtsnBqFXmdrm"
#    "sharedState"
#    "sheetWidth"
#    "shouldCenterButtons"
#    "showCloseButton"
#    "showDescLabel"
#    "showHomePushToSubscribe"
#    "showNetLog"
#    "showTime"
#    "shownGifNames"
#    "showsPageControl"
#    "shuffledItems"
#    "sideLength"
#    "signKey"
#    "signedParams"
#    "singleView"
#    "sizeStr"
#    "sizeText"
#    "slice"
#    "sortedArray"
#    "sortedFileURLs"
#    "source"
#    "speedFactor"
#    "srcRowBytes"
#    "stack"
#    "stackView"
#    "startButton"
#    "startColor"
#    "startGetAiDrawDataTime"
#    "startOffset"
#    "stateSubscriber"
#    "statusBarHeight"
#    "statusChangeHandlers"
#    "statusColor"
#    "statusFont"
#    "statusUpdate"
#    "steps"
#    "storedDate"
#    "storedTimestamp"
#    "stripeColor"
#    "stripeLayer"
#    "stripePath"
#    "stripeSpacing"
#    "stripeWidth"
#    "styleConfig"
#    "styleOptions"
#    "styleScrollView"
#    "subFrame"
#    "subPeriodLabel"
#    "subViewDataArray"
#    "submitButton"
#    "subscribeInfo"
#    "subscribePriceCacheTime"
#    "subscribeProVC"
#    "subscribeVCbackKeepDrawData"
#    "subscriptionStackView"
#    "subscriptionStackbackView"
#    "subtitleLabel"
#    "successCount"
#    "swiperCacheKey"
#    "swiperClickParamsType"
#    "swiperData"
#    "swiperDataArr"
#    "swiperImageStringDataArr"
#    "swiperViewHeight"
#    "swperItem"
#    "tabBarTop"
#    "tapGestureResultImageView"
#    "tapGestureResultImageView1"
#    "tapVipBtn"
#    "targetArr"
#    "targetFrame"
#    "targetHeight"
#    "targetSizeInPoints"
#    "targetVC"
#    "targetWidth"
#    "targetY"
#    "tempActiveColor"
#    "tempArr"
#    "tempCoefficient"
#    "tempFileName"
#    "tempFileURL"
#    "tempIMV"
#    "tempImageView"
#    "tempInactiveColor"
#    "tempInsetRect"
#    "tempMonitor"
#    "tempObjectVTAChxxyKt"
#    "tempQueue"
#    "temporaryDirectoryURL"
#    "temporaryFileURL"
#    "termsStackView"
#    "text1"
#    "text2"
#    "text2video"
#    "textAndRebuttonSuperView"
#    "textContent"
#    "textInputViewH"
#    "textToVideoVC"
#    "textViewMaxY"
#    "thirdLevelOriginData"
#    "thirdNav"
#    "threeLevelWordsArr"
#    "threeSelectKey"
#    "threebuttonWidth"
#    "timeColor"
#    "timeElapsed"
#    "timeFont"
#    "timeLabel"
#    "timeObserver"
#    "timeString"
#    "timesDesc"
#    "tipContainerHeight"
#    "tipL"
#    "tipl"
#    "tips"
#    "tipsView"
#    "tipsViewLR"
#    "tiptext"
#    "titleAndIMGMargin"
#    "titleH"
#    "titleL"
#    "titleLb"
#    "titleOffsetY" 
#    "titleStr"
#    "titleViewSelectIndex"
#    "tmpDir"
#    "todayCanCheckIn"
#    "todayUseLess"
#    "topBtnWidth"
#    "topBtnsView"
#    "topContainer"
#    "topGradualBgView"
#    "topHeight"
#    "topImageView"
#    "topImageViewH"
#    "topImageViewImageObserver"
#    "topImageWidth"
#    "topIndex"
#    "topLineView"
#    "topMaskLayer"
#    "topOffset"
#    "topSafeAreaHeight"
#    "topTipLabel"
#    "topTitleView"
#    "topVC"
#    "toplogoImgV"
#    "totalContentWidth"
#    "totalCount"
#    "totalDuration"
#    "totalHeight"
#    "totalImgWidth"
#    "totalItems"
#    "totalMemoryInGB"
#    "totalMinutes"
#    "totalNum"
#    "totalPage"
#    "totalPages"
#    "totalSaveCount"
#    "totalScreenHeight"
#    "totalSeconds"
#    "totalSecondsRemainder"
#    "totalSteps"
#    "totalTimes"
#    "totalWidth"
#    "touchPoint"
#    "transaction"
#    "transactionRecords"
#    "transformedCoords"
#    "transitionDuration"
#    "trashUrl"
#    "trimmedText"
#    "trimmedUrlString"
#    "trueOffset"
#    "tryAgainBtn"
#    "tryAgainButton"
#    "tryAgainL"
#    "ttvInputString"
#    "twoSoloPhotos"
#    "twoUploadCenterDottedLine"
#    "twoUploadContainerView"
#    "type2"
#    "typeDescription"
#    "uPoint"
#    "uiManager"
#    "uncompressURL"
#    "unzipProgress"
#    "updateInfo"
#    "updatedSections"
#    "updatedText"
#    "uploadBtn"
#    "uploadButton"
#    "uploadPicButton"
#    "uploadRetryCount"
#    "uploadSuccessPicUrlArr"
#    "uploading"
#    "urlString"
#    "urlsDataArr"
#    "useIsVip"
#    "useTime"
#    "userDefaults"
#    "userDefaultsKey"
#    "userHaveDiamond"
#    "userId"
#    "userInfoV"
#    "userIsVip"
#    "userLabel"
#    "userProVipState"
#    "userToken"
#    "userVipState"
#    "v2vs"
#    "v2vsArray"
#    "validOffsetX"
#    "validProgress"
#    "validUrls"
#    "valueColor"
#    "vcname"
#    "verCode"
#    "versionL"
#    "verticalPadding"
#    "verticalSpacing"
#    "videoButton"
#    "videoData"
#    "videoLoadingIndicator"
#    "videoModels"
#    "videoPlayerManager"
#    "videoSection"
#    "videoSectionsModel"
#    "videoUrls"
#    "videoView"
#    "videoViewTappedBlo"
#    "viewAspect"
#    "viewBeforeColor"
#    "viewBgColor"
#    "viewHeight"
#    "vipButton"
#    "vipButtonTappedBlo"
#    "vipDescArr"
#    "vipI"
#    "vipIcon"
#    "vipPicUrlsArr"
#    "vipStatu"
#    "vipStatus"
#    "vipStatusTip"
#    "vipTitle"
#    "vseconds"
#    "wasAnimating"
#    "webConfiguration"
#    "wenhaoButton"
#    "withdrawButton"
#    "wordCountLabel"
#    "wordsArr"
#    "workItem"
#    "worksVC"
#    "wrapperView"
#    "wsUrl"
#    "xStride"
#    "yStride"
#    "ytime"
)
